name = "my-worker"
type = "javascript"

account_id = "9dd00554d5e77e99bbf7668707db6932"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2021-10-24"
entry-point = './src'
kv_namespaces = [
  {binding = "MY_KV", id = "1a7359526de1485ea45c3d01681bbc1a"},
  # {binding = "PREVIEW_KV", preview_id = "6c055d2410b24e41928c01f4972217e6"}
]

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
